name: "Set up pyspark environment"
description: "Set up pyspark environment"
inputs:
  python_version:
    description: "Python version to install"
    required: true
#   pyproject_toml:
#     description: "Path to pyproject.toml"
#     required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: "test output"
      shell: "bash"
      run: |
        ls
        pip install .