name: "Set up pyspark environment"
description: "Set up pyspark environment"
inputs:
  python_version:
    description: "Python version to install"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: "pip install ."
      shell: "bash"
      run: |
        pwd
        ls
        pip install .