name: Docker build and test
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up pyspark
        uses: "./.github/actions/python-env-setup"
        with:
          python_version: ${{ matrix.python-version }}

      - run: python -m pytest
