name: pytests
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Set up pyspark
        uses: "./.github/actions/python-env-setup"
        with:
          python_version: ${{ matrix.python-version }}

      - run: pip install .

      - name: Run pylint
        run:
          pylint foo.py > pylint_output.txt

      - name: pylint output to PR on failure
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: pylint_output
          mode: upsert
          filePath: pylint_output.txt


      - run: python -m pytest
