name: pytests
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install .

      - name: Run pylint
        run: |
          echo "# Pylint Output" > pylint_output.txt
          pylint src/ >> pylint_output.txt

      - name: run pytests
        run: |
          echo "" >> pylint_output.txt
          echo "# Pytest Output" >> pylint_output.txt
          python -m pytest tests/ >> pylint_output.txt

      - name: pylint output to PR on failure
        if: always()
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: pylint_output
          mode: upsert
          filePath: pylint_output.txt
