name: "Databricks notebook checks"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  gather-notebooks:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: "true"
          files: |
            notebooks/Jobs/**

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was added"
          done

  check-notebook:
    runs-on: ubuntu-latest
    needs: gather-notebooks
    strategy:
      matrix:
        notebook: ${{ fromJSON(needs.gather-notebooks.outputs.changed_files) }}
    steps:
      - run: echo $notebook